Added Autofill toolbar button
explosivegaming/scenario pull request #175
Opened 2020-08-17 21:10 UTC by bbassie

- May needs to be changed to have a left flow with option;

2020-08-19 22:15 UTC, bbassie reviewed
Comments on the current status of the PR

2020-08-19 22:15 UTC, bbassie commented on config/gui/autofill.lua
> +	}
Not sure about this config layout may still need to be changed

2020-08-19 22:15 UTC, bbassie commented on modules/gui/autofill.lua
> +end
This part is also going to need some changes because the performance is not optimal also because of the config.

2020-08-19 22:15 UTC, bbassie commented on modules/gui/autofill.lua
> +end
Temporary function should't need it when config changed.

2020-08-19 22:15 UTC, bbassie commented on config/gui/autofill.lua
> +		},
Locomotive part not working need to figure out why.

2020-09-02 23:52 UTC, Cooldude2606 requested changes
General note about some functions: where you have function of the form `print({...})` you can change it to `print{...}` other examples include `can_insert` and `insert`

2020-09-03 00:06 UTC, bbassie commented on config/gui/autofill.lua
> +local steel_furnace = 'steel-furnace'
ecadbd6

2020-09-03 01:47 UTC, bbassie commented on modules/gui/autofill.lua
> +-- @element header_toggle
e23092a

2020-09-03 01:49 UTC, bbassie commented on modules/gui/autofill.lua
> +toggle_section
620051d

2020-09-03 01:49 UTC, bbassie commented on modules/gui/autofill.lua
> +end)
Maybe later but is hard to test locally for me so you can add it if its needed.

2020-09-03 01:50 UTC, bbassie commented on config/gui/autofill.lua
> +local default_autofill_item_settings = {
f149e44

2020-09-03 01:50 UTC, bbassie commented on locale/en/gui.cfg
> +filled=Autofilled the __1__ with __2__ __3__
e52f06d

2020-09-03 01:50 UTC, bbassie commented on config/gui/autofill.lua
> +default_autofill_item_settings = nil
Removed it altogether now.

2020-09-03 02:18 UTC, Cooldude2606 commented on modules/gui/autofill.lua
> +end)
Testing locally is not effected by the data sync. Because you are not connected to the server a fake responce will be triggered internally after 5 seconds to ensure that scripts still work. But I agree it can be done later as data syncing is not a requirement.

2020-09-03 16:02 UTC, Cooldude2606 requested changes
Everything else is good, just one change suggested.

2020-09-03 16:02 UTC, Cooldude2606 commented on modules/gui/autofill.lua
> +end)
Do toggle_item_button_empty and amount_textfield_empty require names? Do they even require the flows?
I suggest removing the flows and removing the names from the empty elements so factorio will auto assign a unique name. This will also mean that you dont need to use a function to define the empty elements.

2020-09-04 22:49 UTC, bbassie commented on modules/gui/autofill.lua
> +end)
ef823f2

2020-09-06 00:21 UTC, Cooldude2606 requested changes
I thought I had already pointed this out but I guess I missed it. You use string.len on string literals which can be simplified to constants. These apear on lines 75, 133, and 175. Everything else is fine.

2020-09-07 18:27 UTC, Cooldude2606 requested changes
All of the code is now fine, there are just some style issues that need addressing.

2020-09-07 18:27 UTC, Cooldude2606 commented on locale/en/gui.cfg
> +toggle-entity-tooltip=Toggle the autofill of __1__s
My previous suggestion of adding the s on the end was wrong. I did not know that you were using rich text for `__1__` which leeds to a strange looking tooltip.
![tooltip](https://i.imgur.com/2ZHSzoA.png)

2020-09-07 18:27 UTC, Cooldude2606 commented on modules/gui/autofill.lua
> +        entity_table.style.padding = 3
I would suggest aligning the table to be centered to avoid a large gap on one side.
![gap](https://i.imgur.com/9bE4gPu.png)

2020-09-07 18:27 UTC, Cooldude2606 commented on modules/gui/autofill.lua
> +    end
I think that setting the style here is resetting the padding causing the icons for the cross and tick to be different sizes. If not then it might be best to having a different padding for each icon to make them apear the same size.
![sizes](https://i.imgur.com/agMwu8i.png)

2020-09-07 18:27 UTC, Cooldude2606 commented on modules/gui/autofill.lua
> +    scroll_table.style.vertical_spacing = 0
I think there may still be some horizontal spacing which is causing these gaps on both sides. These gaps show both when the sections are closed and when they are open.
![gaps](https://i.imgur.com/dCLZZS9.png)

2020-09-08 14:24 UTC, bbassie commented on modules/gui/autofill.lua
> +    scroll_table.style.vertical_spacing = 0
I think you've got an older version because fixed this some commits ago. And cannot reproduce.

2020-09-08 14:24 UTC, bbassie commented on modules/gui/autofill.lua
> +    end
They have the same size and padding is pixel perfect the same for both so I don't see any change needed.
![ShareX_tshXrSEgRi](https://user-images.githubusercontent.com/17990055/92489090-a2430380-f1ef-11ea-9dcf-a60989b26198.png)
(padding top and bottom is also the same for both buttons!)

2020-09-08 14:25 UTC, bbassie commented on modules/gui/autofill.lua
> +        entity_table.style.padding = 3
They are centered now:
![factorio_OpiKeTuIuK](https://user-images.githubusercontent.com/17990055/92489270-e7ffcc00-f1ef-11ea-8ecb-303eadcc965f.png)

2020-09-08 14:28 UTC, bbassie commented on locale/en/gui.cfg
> +toggle-entity-tooltip=Toggle the autofill of __1__s
https://github.com/explosivegaming/scenario/pull/175/commits/afcd16c56e30fcb3bc3bd3bf7935c4fc9b952ce4

2020-09-08 17:20 UTC, Cooldude2606 requested changes
Autofill is not working, the toggle_item_button does not change state when clicked.

2020-09-09 19:59 UTC, Cooldude2606 commented
Last suggestion and then I will be happy to merge: increase the space between the inserted messages so that it is closer to what the base game pickup messages are. (images are at different zoom levels)
![zoomOne](https://i.imgur.com/Sde4Lrh.png) ![zoomTwo](https://i.imgur.com/OX0Kyxp.png)

2020-09-11 18:50 UTC, bbassie commented
> Last suggestion and then I will be happy to merge: increase the space between the inserted messages so that it is closer to what the base game pickup messages are. (images are at different zoom levels)
> ![zoomOne](https://camo.githubusercontent.com/505ef5f5da160e34623771e2fbb23cbc8a35d584/68747470733a2f2f692e696d6775722e636f6d2f536465344c72682e706e67) ![zoomTwo](https://camo.githubusercontent.com/46b65e65b638c11145877de4d868e3e20e3c724a/68747470733a2f2f692e696d6775722e636f6d2f4f58304b7978702e706e67)

Fixed: https://github.com/explosivegaming/scenario/pull/175/commits/c46244e7edf7adc3df449c12077380ce21405960
![image](https://user-images.githubusercontent.com/17990055/92961881-55ba2b00-f470-11ea-855a-84f640d9ad9b.png)

2020-09-12 02:00 UTC, Cooldude2606 approved these changes
Everything looks good now.

2020-09-12 02:01 UTC, merged