Add command /tag-color
explosivegaming/scenario pull request #180
Opened 2020-11-03 23:50 UTC by bbassie

Adds a command to change the color of a tag, a fun thing for what I thought supporters and up to use. This also makes longer tags more readable.
![factorio_Kn87h8jwlQ](https://user-images.githubusercontent.com/17990055/98052915-af6b2000-1e37-11eb-8467-25c1b57eecbf.png)

2020-11-03 23:51 UTC, bbassie commented
Not sure if I did the data part right.

2020-11-06 14:50 UTC, Cooldude2606 requested changes
Everything looks good, the datastore methods are used correctly.
You mention that you make longer tags look nicer, what change have you made to do this?

2020-11-06 14:50 UTC, Cooldude2606 commented on config/expcore/command_color_parse.lua
> +    player.print("invalid")
This print is not required as reject will print the error message to the player.

2020-11-06 21:47 UTC, Cooldude2606 approved these changes
Every looks good, ill be happy to merge this.

2020-11-06 21:48 UTC, merged