Corpse light and line addition
explosivegaming/scenario pull request #191
Opened 2020-11-08 19:10 UTC by bbassie

![image](https://user-images.githubusercontent.com/17990055/98481946-57009d80-21fe-11eb-851f-646e577b8b4d.png)

2020-11-11 00:57 UTC, Cooldude2606 requested changes
Nice feature, a way to hide all tracers would be nice but is not required.
There are two optimizations which should be made.

2020-11-11 00:57 UTC, Cooldude2606 commented on modules/addons/death-logger.lua
> +        for _, death in pairs(deaths) do
Due to table.insert being used the newest death will always be at the end of the array.
It will save alot of iterations by starting at the end of the array and counting backwards.
`for index = #deaths, 1, -1 do`

2020-11-11 00:57 UTC, Cooldude2606 commented on modules/addons/death-logger.lua
> +            if death.player_name == player.name and death.corpse and death.corpse.valid then
Starting from the end of the list means you get newest to oldest death entries.
If you only want the latest death then I would break as soon as a matching name is found.
If you want all valid corpses then I would add a break condidition which checks `time_of_death` against the current game tick. If it is longer than 15 minutes for any death entry then you know all older corpses will have expired, and it is safe to exit the loop.
Based on above add either a break for a single corpse or a break based on `time_of_death`

2020-11-15 17:40 UTC, bbassie commented on modules/addons/death-logger.lua
> +        for _, death in pairs(deaths) do
Fixed

2020-11-15 17:40 UTC, bbassie commented on modules/addons/death-logger.lua
> +            if death.player_name == player.name and death.corpse and death.corpse.valid then
Added

2020-11-15 23:24 UTC, Cooldude2606 approved these changes
Everything looks good and requested changes have been implemented.

2020-11-15 23:25 UTC, merged