Tasklist refactor to match the new warp system
explosivegaming/scenario pull request #195
Opened 2021-01-24 01:03 UTC by bbassie

* Removed the ability to pass `task_number` to `Task.add_task`
* Unified button styles of the Gui
* Made task-list code simular to the new warp-list

2021-01-24 03:03 UTC, Cooldude2606 commented
Git actions have beeen fixed, the fix has been merged into your pr.

2021-04-10 19:32 UTC, bbassie commented
Implemented a base working version of the task list with a new redesign.

2021-04-11 18:10 UTC, bbassie commented
@Cooldude2606 I don't know what else to add to this, so it should be ready for review if you have the time!

2021-04-11 21:10 UTC, Cooldude2606 commented
A few small changes have been discussed which can be implemented in this PR with an option for another rewrite for the future.
Changes require for this PR:
- Although the thin buttons look nice, the icons are cropped as a result and so the buttons should be made bigger again.
- Changing the text field to a text box will allow for multiline formatting at the cost of on_confirmed. But we find this is acceptable and will allow for a "title" for a task which is defined as the first line of the message. (Similar to git messages)
- The confirm edit button should have a tooltip for why it is disabled.

Change for future redesigns:
- Rewrite of the control module to allow for easy use of a box list element rather than the custom hack which has been created here. This could include new functions for getting a task based on force and index (rather than id) and events for tasks being added, removed, and edited (rather than just updated).

Once the required UI changes are made I will review the code.

2021-04-13 22:28 UTC, bbassie commented on modules/gui/task-list.lua
> +end
@Cooldude2606 Maybe you have a better idea on how to do this...

2021-04-13 22:29 UTC, bbassie commented
Implemented the changes requested. Lint is failing on for loop 333, maybe you know something better.

2021-04-13 23:23 UTC, Cooldude2606 commented on modules/gui/task-list.lua
> +end
You can use string.match rather than string.gmatch. Here is an example:
`local d, m, y = string.match("14/04/2020", "(%d+)/(%d+)/(%d+)")`

2021-04-19 22:35 UTC, Cooldude2606 requested changes
Mostly comments with small adjustments needed.
Considering the amout code there was very few errors, and I found some useful features I can add to GUI core.
There is one point I would like to discuss, because task details can vary in size I personally feel the buttons should be moved to the top right of "Task details". This would make them be in a consistent place regardless on the size of the task. However, the confirm and discard buttons are still great at the bottom as you select them last.

2021-04-19 22:35 UTC, Cooldude2606 commented on modules/gui/task-list.lua
> +    function(_, parent)
Due to how close this is to the trivial case, I feel the GUI core should be changed to allow a custom non unique name.
This would be an easy change to make in core, but may require a `id` property depending on the value I want `name` to hold.
I will make this feature request, and might implement it for the next release.

2021-04-19 22:35 UTC, Cooldude2606 commented on modules/gui/task-list.lua
> +        scroll_pane.style.maximal_height = 300
This max height should be adjusted to contain a whole number of tasks. Currently it contains 10 with some of the 11th showing.

2021-04-19 22:35 UTC, Cooldude2606 commented on modules/gui/task-list.lua
> +            caption = "Do x or y"
Is this caption needed when it always gets overriden?

2021-04-19 22:35 UTC, Cooldude2606 commented on modules/gui/task-list.lua
> +    local trimmed = (string.gsub(str, "^%s*(.-)%s*$", "%1"))
I dont think the outter most brackets are required.

2021-04-19 22:35 UTC, Cooldude2606 commented on modules/gui/task-list.lua
> +            name = name,
Because of how common cases like this are, I feel I should allow the core to generate these.
Perhaps with a `name = Gui.argument_value` in the define table, and extent this to work for any property like captions.
I will add this as a feature request.

2021-04-25 21:05 UTC, Cooldude2606 approved these changes
All highlighted issues were resolved and the code is ready to merge.
However, I will still like to discuss the best location for "edit, delete, close" before we merge.
Also I will request a review from mark to check the locale files and comments.

2021-04-25 21:23 UTC, bbassie commented
> All highlighted issues were resolved and the code is ready to merge.
> However, I will still like to discuss the best location for "edit, delete, close" before we merge.
> Also I will request a review from mark to check the locale files and comments.

Best I can come up with:
![image](https://user-images.githubusercontent.com/17990055/116010066-29c57180-a61d-11eb-9114-8a2c3bd75fad.png)
It's still a bit meh but maybe better than 3 buttons in a row?

2021-04-25 21:59 UTC, Cooldude2606 commented
> It's still a bit meh but maybe better than 3 buttons in a row?

Yeah it is the three buttons that is off putting for me, since it seams very cramped.
I think it looks good having the two buttons, close will probably be the least used so its ok for it to have less contrast.
(least used because people will leave a task open, then either switch to a different one or delete it when finished)
If you also think it looks better than the three button style, then I would go for it; if not we should ask others for an opinion.

2021-04-26 01:00 UTC, Cooldude2606 commented
Changes work as intented; however, your `vertical_flow` is not vertical and if it was vertical then it would break styling. I would name it `horizontal_flow` `title_flow` or just `flow`.

2021-04-26 19:47 UTC, mark9064 approved these changes
Large PR so quite a few comments, but it's just a lot of little things :smile:

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +-- @element no_tasks_found
`@element` is incorrect?

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +--- Button to close the view task footer
`view task footer` or `task view footer`, pick one
Module wide

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +--- Parce a string into a message object with title and body
```suggestion
--- Parse a string into a message object with title and body
```

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +    -- Trimm the spaces of the string
```suggestion
    -- Trim the spaces of the string
```

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +        -- If it doesn't match the patter return the str as a title
```suggestion
        -- If it doesn't match the pattern return the str as a title
```
str is one of the arguments, which specific string is this referring to (at least to me str is often used as a generic type for strings)

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +--- Button to discard the changes
Since L387 exists, it'd be nice if these docstrings were slightly more specific. Probably minor though
Applies in a few other places actually, like subfooter in tasklist container

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +        -- Return the exteral container
```suggestion
        -- Return the external container
```

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +-- @element toggle_left_element
I don't actually know what `@element` signifies but this one also doesn't seem correct

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +        -- edit_task_element.hovered_sprite = 'utility/warning_icon'
Dead code? (same as line a couple below)

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +            -- Update the task view if the player has the changed task selected
Maybe better phrased as `changed the(ir) selected task`? Not 100% sure what's going on here so ignore if I've misunderstood

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +        -- If the selection has a old state re-enable the button list element
```suggestion
        -- If the selection has an old state re-enable the button list element
```

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +        -- If the selection has a old state re-enable the button list element
Or maybe `previous state` if more appropriate? (time vs sequence)

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +            -- If new state nil then hide footer elements and set editing to nil for old_state
```suggestion
            -- If new state is nil then hide footer elements and set editing to nil for old_state
```

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +    -- Update the new task button and create footer incase the user can now add them
```suggestion
    -- Update the new task button and create footer in case the user can now add them
```

2021-04-26 19:47 UTC, mark9064 commented on modules/gui/task-list.lua
> +        -- Set selected to the same value, this will make sure if player was in a editing state he will leave it if no permissions.
I'm not a fan of how this is phrased. Maybe something like `Set selected to the same value, this will make sure if the player was in a editing state they will leave it if <they no longer have permission to edit?>`(I'm not totally sure what's happening here so amend as needed)

2021-04-27 21:14 UTC, bbassie commented on .github/workflows/dev-deploy.yml
> +        uses: leafo/gh-actions-lua@v8.0.0
Because the GitHub actions stopped working and @Cooldude2606 force pushed the changes or something like that

2021-04-27 21:54 UTC, bbassie commented on modules/gui/task-list.lua
> +-- @element toggle_left_element
@Cooldude2606 I was also looking into this, but maybe you can clarify?

2021-04-27 22:00 UTC, bbassie commented on modules/gui/task-list.lua
> +            -- Update the task view if the player has the changed task selected
Ignored, basically this is in a loop where it loops over all the players. If a player has the task that is being updated selected it will update the task view elements for them.

Updated the comment to hopefully be more specific in a later commit.

2021-04-27 22:12 UTC, bbassie commented on modules/gui/task-list.lua
> +        -- If the selection has a old state re-enable the button list element
Changed this and some other occurrences of old and new

2021-04-29 16:54 UTC, Cooldude2606 commented on .github/workflows/dev-deploy.yml
> +        uses: leafo/gh-actions-lua@v8.0.0
Yes this change was to correct CI issues, the changes had to be merged here for the CI to pass, all other PRs were created after the change was commited to dev.

2021-04-29 17:11 UTC, Cooldude2606 commented on modules/gui/task-list.lua
> +-- @element toggle_left_element
The tag `@element` is a cosmetic feature on the docs used to signify that the module adds gui elements.
As such the name is also cosmetic, but when possible should match the variable name.
In this case there is no variable so the name describes what it does.
Perhaps `task_list_toggle` would be better.
Also there are many other cases where `toggle_left_element` is used due to neglect.
Example from previous doc generation:
![docs](https://i.imgur.com/tmigZDs.png)

2021-04-29 20:00 UTC, Cooldude2606 commented on modules/gui/task-list.lua
> +-- @element toggle_left_element
Due to this issue existing across multiple files, it will be addressed on a seperate pull request.

2021-04-29 22:04 UTC, merged