Clear join message & fixing saving quickbar
explosivegaming/scenario pull request #200
Opened 2021-02-13 14:03 UTC by oof2win2

Same as #199 but not merging to master & removed my method of assigning roles over RCON (`/interface` should be used instead)
## Command to clear join message
New command to clear your join message (`/join-message-clear`)
## Save-quickbar bugfix
The quickbar sync had an issue where items with unique IDs would be just replaced by general items, i.e. a deconstruction planner with a specific filter would be replaced by a generic deconstruction planner. This has been fixed by checking if an item is a list of set items, which include:
- Spidertron remotes (unique ID to spidertron, changes every time spidertron dies, etc)
- Deconstruction planner
- Upgrade planner
- Blueprint book
- Blueprint
If the item is in this list, it is ignored and not pushed to the user's settings of quickbar syncing.
Extended version of d65a1fe0fefec17dd372860d192ac3300fbe72d8

2021-02-13 14:06 UTC, bbassie approved these changes

2021-02-13 14:09 UTC, bbassie requested changes

2021-02-13 14:09 UTC, bbassie commented on modules/data/greetings.lua
> +:register(function(player, message)
Just remove message argument.

2021-02-13 14:10 UTC, bbassie approved these changes

2021-02-13 16:27 UTC, Cooldude2606 requested changes
Two changes which can be made to increase preformance of the code, always define static tables outside of functions and use hash tables when possible.

2021-02-13 16:27 UTC, Cooldude2606 commented on modules/data/quickbar.lua
> +
- A constant table like this should be defined outside side the function call, this will improve preformance by removing the need to allocate memory for the table.
- Using a hash table is much faster than iteration becuase of of the seperation between C and Lua. I would remove the contains function and using a hash table in the following form:
```lua
-- Hash table
local ignoredItems = {
    ["blueprint"] = true
}

-- Test if ignored
local ignored = ignoredItems[slot.name]
```

2021-02-14 04:04 UTC, Cooldude2606 approved these changes
Required changes were made.

2021-02-14 04:06 UTC, merged