Implement nuke protect, fix move_items
explosivegaming/scenario pull request #229
Opened 2022-05-14 21:29 UTC by oof2win2

Changed _C.move_items* to be _C.copy_items_stack, which copies items, and _C.move_items_stack, which moves items.

Added an addon called `nukeprotect`, which prevents players without a flag from having specific items in their inventories.

2022-05-15 01:21 UTC, Cooldude2606 requested changes

2022-05-15 01:21 UTC, Cooldude2606 commented on config/nukeprotect.lua
> +	ignore_permisison = "bypass-nukeprotect" -- @setting ignore_permisison The permission that nukeprotect will ignore
I would include an option for `ignore_admins` which is true by default, this is to allow the module to be used outside of the Roles module.

2022-05-15 01:21 UTC, Cooldude2606 commented on modules/addons/nukeprotect.lua
> +	end
This can be moved into its own function to prevent repetition.

2022-05-15 01:21 UTC, Cooldude2606 commented on modules/addons/nukeprotect.lua
> +Event.add(defines.events.on_player_ammo_inventory_changed, function(event)
Because the config is static, you can avoid adding handlers if the arrays are empty.
eg `if #config.ammo > 0 then --[[ register ammo handler --]] end`

2022-05-15 08:17 UTC, oof2win2 commented
I added the new config, though I'm not sure if this is a good way to do it so that it is "modular".

2022-05-15 16:09 UTC, Cooldude2606 requested changes
Firstly, I dont see any reason to use `tostring` on the keys.
Secondally, if you want to make it modular then you should include the event name in the config:
```
{
  {
    inventory = defines.inventory.character_ammo,
    event = defines.events.on_player_ammo_inventory_changed,
    items = {
      ["atimic-bomb"] = true
    }
  }
}
```
This will alow you to use a for loop within the module code.
```lua
for _, area in ipairs(config) do
  if #area.items > 0 then
    Event.add(area.event, ...)
  end
end
```

2022-05-15 16:09 UTC, Cooldude2606 commented on config/expcore/roles.lua
> +    ["oof2win2"]={"Senior Administrator","Moderator","Senior Backer","Supporter"},
Accidental commit.

2022-11-12 21:40 UTC, oof2win2 commented
Implemented the desired modularity of the code

2022-12-09 21:08 UTC, Cooldude2606 approved these changes
LGTM

2022-12-09 21:09 UTC, merged