Add ban and unban logging for FAGC clientside bot support
explosivegaming/scenario pull request #231
Opened 2022-09-14 19:49 UTC by oof2win2

https://github.com/FactorioAntigrief/FactorioAntigrief/issues/124

2022-09-18 02:14 UTC, Cooldude2606 requested changes

2022-09-18 02:14 UTC, Cooldude2606 commented on modules/addons/fagc.lua
> +	game.write_file("fagc-actions.txt", "", true, 0)
This needs to be false in order to overwrite the file.

2022-09-18 02:14 UTC, Cooldude2606 commented on modules/addons/fagc.lua
> +	local text = "ban;\"" .. e.player_name .. "\";\"" .. (e.by_player or "") .. "\";\"" .. (e.reason or "") .. "\""
Why use both quotes and semi-colons where neither are possible in usernames.
It may even be better to keep this csv compliant, meaning use `,` to seperate each part and use `"` around the reason.

2022-09-20 09:57 UTC, oof2win2 commented on modules/addons/fagc.lua
> +	local text = "ban;\"" .. e.player_name .. "\";\"" .. (e.by_player or "") .. "\";\"" .. (e.reason or "") .. "\""
Resolved

2022-09-25 00:10 UTC, Cooldude2606 approved these changes

2022-09-25 00:10 UTC, merged