Feature Update
explosivegaming/scenario pull request #237
Opened 2023-02-13 13:13 UTC by PHIDIAS0303

- [ ] **1 Report Jail**
Now it looks up if an active moderator is in-game.
Otherwise, then uses logic to check player data once.

- [x] **2 Sever UPS Display**
Slightly adjust the display a bit lower so it don't block the clock

- [ ] **3A Player Data Ratio**
Add ratio in the display

- [ ] **3B Player Data Lookup**
Allow other player data lookup in-game

- [x] **5 Spawn Area**
Optional edit to allow customized generation.
This slightly boost the starting patch so it is faster to start.

- [ ] **6 Vlayer**
Optional virtual layer module to allow sending solar panel and battery inside.
This could allow saving a lot of space.

- [ ] **7 Personal Logistic Slot**
Optional setting for personal logistic slot. only for member and above.

- [ ] **8 Auto Miner Deconstruction**
Optional, an attempt for automatic miner deconstruction

2023-02-13 15:27 UTC, Cooldude2606 commented
Does point 3B cover #226 ? I feel like it does so once this is merged that issue can be closed.

Also point 8 sounds really cool to have, a balance suggestion for it is to have the "area" limited but with the option of expanding it using landfill. Another is to launch it into space but that feels far too costly.

2023-03-07 06:26 UTC, PHIDIAS0303 commented
most stuff is done now, basically need some more testing from others

2023-03-12 14:31 UTC, Cooldude2606 commented on modules/addons/compilatron.lua
> +    local compi = surface.create_entity {name='compilatron', position=pos, force=game.player.force}
This is incorrect. Please revert.
1) Compilatron should also be spawned to the "neutral" force.
2) "game.player" is nil during "on_player_created" because it is not a command.

2023-03-12 14:43 UTC, PHIDIAS0303 commented on modules/addons/compilatron.lua
> +    local compi = surface.create_entity {name='compilatron', position=pos, force=game.player.force}
:white_check_mark:

2023-03-12 14:56 UTC, Cooldude2606 commented on modules/addons/advanced-start.lua
> +                end
Should you not include `position` in this config so you can ensure the equipment fits independent of the order they are inserted?

2023-03-12 15:00 UTC, Cooldude2606 commented on modules/addons/advanced-start.lua
> +            local armor = player.get_inventory(defines.inventory.character_armor)[1].grid
1) There is no reason to check if `player` is nil in this conditional, `player` is never nil during `on_player_created`
2) This code does not ensure the items are added to the armour which you insert. It could be the case that armour is inserted during the previous steps which does not have an equipment grid. This then causes no equipment to be given to the player.

2023-03-12 15:43 UTC, Cooldude2606 requested changes
All "addons" have been reviewed. Other modules, configs, and language files have not yet been reviewed.

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/discord-alerts.lua
> +            ['Location']=game.players[event.player_index].position
Why are you getting the player position and not the entity position? This would save you needing to index the player array.

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/protection-jail.lua
> +    end
Is this actully useful? It means the person can contiune to remove items, and the moderator has no way to know its happening unless they check discord. But if they get jailed then this appears in chat and the moderator can react.

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/report-jail.lua
> +        elseif #Reports.get_reports(player) > 1 then
1) `#Reports.get_reports(player) > 1` is always true because this event is triggered when a report is added. Therefore this condition is not required.
2) `player.online_time > 108000` should not be considered because it makes people auto jail immune after 30 minutes, and does not fix the issue you see with this system.
Suggestion) Use `total_playtime > math.max(108000, player.online_time * 2)` and jail the player when this is true.

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/spawn_area.lua
> +    end
Bad formatting.

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/spawn_area.lua
> +            protect_entity(turret)
Incorrect. Please revert.
The spawn turrets should be on the `spawn` force, this is done through the second argument to `protect_entity`

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/spawn_area.lua
> +            inv.insert{name=config.turrets.ammo_type, count=20}
There is no reason to change this to 20, in fact it would likly cause the turrets to have less ammo because it must wait to have less than 80 before refilling.

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/spawn_area.lua
> +            local belt_entity = surface.create_entity{name=belt_type, position=pos, force='player', direction=belt[3]}
Incorrect. Please revert.
The belts should not be on the player force. They should either be on `spawn` or `neutral` (I do not remember the rational for picking `neutral` over `spawn` in this case)

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/spawn_area.lua
> +        entity = surface.create_entity{name=entity[1], position=pos, force='player'}
Incorrect. Please revert. Spawn entities should either be on `spawn` or `neutral` (I do not remember the rational for picking `neutral` over `spawn` in this case)

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/spawn_area.lua
> +    for k, _ in ipairs(config.resource_tiles.resources) do
No reason to be using the index `k` here. Change to `_, resource`.

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/spawn_area.lua
> +    for k, _ in ipairs(config.resource_patches.resources) do
No reason to be using the index `k` here. Change to `_, resource`.

2023-03-12 15:43 UTC, Cooldude2606 commented on modules/addons/station-auto-name.lua
> -                entity.backer_name = string.format("[L] [img=%s.%s] %s %s (%s)", Item_ore_fluid, item_name, item_name2, entity.backer_name, Angle( entity ))
1) Why are you removing the name formating (first letter as a capital and removing `-` from the name). Please revert.
2) Why are you removing the compass bearing? If you would like this removed then you can add this as a config option.

2023-03-12 18:18 UTC, PHIDIAS0303 commented on modules/addons/protection-jail.lua
> +    end
there are text displayed in the chat for removing items

2023-03-12 18:21 UTC, PHIDIAS0303 commented on modules/addons/report-jail.lua
> +        elseif #Reports.get_reports(player) > 1 then
not when player have 2 reports?

2023-03-12 18:24 UTC, Cooldude2606 commented on modules/addons/protection-jail.lua
> +    end
Ah I see it is done within the command file, my mistake.

2023-03-12 18:27 UTC, Cooldude2606 commented on modules/addons/report-jail.lua
> +        elseif #Reports.get_reports(player) > 1 then
Ah yes I miss read that; in which case I would suggest:
`Reports.count_reports(player) > 1 and total_playtime > math.max(108000, player.online_time * 2)`

2023-03-12 18:29 UTC, Cooldude2606 commented on modules/addons/station-auto-name.lua
> -                entity.backer_name = string.format("[L] [img=%s.%s] %s %s (%s)", Item_ore_fluid, item_name, item_name2, entity.backer_name, Angle( entity ))
Ah this would be when you are using train limits on a station. In which case point 1 is still valid and should be reverted, but point two should be added as a config with it disabled by default (as to not remove functionality).

2023-03-12 21:41 UTC, Cooldude2606 reviewed
I have re-reviewed the "addon" modules and also completed a review of the "command" modules. The other areas have not yet been reviewed.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/addons/advanced-start.lua
> +        end
Can be changed to `for _, item in pairs(config.armor.grid) do` to match lua convention and reducing the amount of indexing.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/addons/deconlog.lua
> +		add_log(get_secs() .. "," .. msg)
This is no longer in csv format so should be reverted to the orginal string. The inclusion of game.print with its own message is fine however.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/addons/station-auto-name.lua
> +                entity.backer_name = config.station_name:gsub('%icon', '[img=' .. Item_ore_fluid .. '.' .. item_name .. ']'):gsub('%item_name', item_name2):gsub('%backer_name', entity.backer_name):gs
Needs to be formatted better. Eg put each gsub on a new line which is indented.
Also `%y` is incorrect because it uses the x value.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/factorio-control.lua
>    }
The base `factorio-control.lua` should not be edited.

2023-03-12 21:41 UTC, Cooldude2606 commented on .luacheckrc
> +local IGNORE = {'21./%w+_$', '21./^_%w+$', '213/[ijk]', '213/index', '213/key', '611'}
The whole repo already conforms to W611 it is only your PR which does not conform. This is no reason to add it to the ignore list.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/bot_queue.lua
> +Commands.new_command('bot-queue-get', 'Set bot queue')
The description of this command is incorrect. Should be "Get bot queue".

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/bot_queue.lua
> +    return Commands.success
This should not be `game.print` instead use `return Commands.success{'expcom-bot-queue.result', s, f}`

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/bot_queue.lua
> +    return Commands.success
This should not be `game.print` instead use `return Commands.success{'expcom-bot-queue.result', s, f}` or add a custom message to say that the value has been updated.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/cheat-mode.lua
> +    return Commands.success
Because it is not always clear what the current state is; please add a message to the player saying what the new state is.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/friendly_fire.lua
> +    return Commands.success
Because it is not always clear what the current state is; please add a message to the player saying what the new state is.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/friendly_fire.lua
> +Commands.new_command('toggle-friendly-fire', 'Set Friendly Fire')
This should read "Toggle Friendly Fire" not "Set"

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/lawnmower.lua
> +		end
`find_entities_filtered` accepts an array of string for `name` which should be used instead of this condition.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/lawnmower.lua
> +				player.surface.set_tiles({{name='grass-1', position={x, y}}})
Please make an array to store the tile changes and then make a single call to `set_tiles` because api calls can be costly.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/lawnmower.lua
> +    player.surface.destroy_decoratives({position=player.position, radius=range})
Removing grass is not documented in the description. Also what is the purpose of removing grass when there is a per user setting to not render them?

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/pollution.lua
> +    return Commands.success
Please use `return Commands.success{'expcom-pol.clr', player}`

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/pollution.lua
> +    return Commands.success
Please use return `Commands.success{'expcom-pol.off', player}`

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/speed.lua
> +    return Commands.success
Please use `return Commands.success{'expcom-speed.result', string.format("%.3f", amount)}`

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/speed.lua
> +    game.speed = string.format("%.3f", amount)
Can not use `string.format` here because it returns a string and `game.speed` expects a number. Use `math.round(amount, 3)`.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/teleport.lua
> +        from_player.print('Come here my friend')
Does this need to be included? It is very rare for teleport to fail, and when it does it is the fault of the player using the command as there is no room to bring another player.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/teleport.lua
> +        if from_player.driving then from_player.driving = false end
Both of these lines are redundant. `goto_position` is calculated as `position` on line 11. `from_player.driving` is always false because of the condition on line 18.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/teleport.lua
> +                from_player.teleport(goto_position, surface)
The position has already been calculated on line 11 as `position` so this call is not needed.

2023-03-12 21:41 UTC, Cooldude2606 commented on locale/en/commands.cfg
> +manual-result=Set __1__ train into automatic mode.
This should use the extra syntax for singular and plural.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/train.lua
> +    return Commands.success
Please use `return Commands.success{'expcom-train.manual-result', format_number(count)}`

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/train.lua
> +Commands.new_command('manual-train', 'Set Automatic Train')
Description should be `Set all trains to automatic`. Also the name `manual-train` doesn't fit what the command does. I recommend `set-trains-to-automatic`.

2023-03-12 21:41 UTC, Cooldude2606 commented on modules/commands/spawn.lua
> +    end
See comments made in `teleport.lua`

2023-03-13 06:26 UTC, PHIDIAS0303 commented on modules/commands/lawnmower.lua
> +    player.surface.destroy_decoratives({position=player.position, radius=range})
the are some stuff that still show up when having concrete or whatever so only this can handle

2023-03-15 17:09 UTC, Cooldude2606 commented on modules/addons/advanced-start.lua
> +        end
Your new code `for equipment, count in pairs(config.armor.grid) do` does not work. Please use what i described and then `item.equipment` and `item.count`

2023-03-15 17:40 UTC, Cooldude2606 commented on modules/addons/spawn_area.lua
> +    for k, _ in ipairs(config.resource_patches.resources) do
Your new code does not work:
```lua
for _, v in ipairs(config.resource_tiles.resources) do
        if config.resource_tiles.resources[v].enabled then
```
please use:
```lua
for _, resource in ipairs(config.resource_tiles.resources) do
        if resource.enabled then
```

2023-03-15 17:40 UTC, Cooldude2606 commented on modules/addons/spawn_area.lua
> +    for k, _ in ipairs(config.resource_tiles.resources) do
Your new code does not work:
```lua
for _, v in ipairs(config.resource_tiles.resources) do
        if config.resource_tiles.resources[v].enabled then
```
please use:
```lua
for _, resource in ipairs(config.resource_tiles.resources) do
        if resource.enabled then
```

2023-03-15 17:46 UTC, Cooldude2606 commented on modules/addons/station-auto-name.lua
> +                entity.backer_name = config.station_name:gsub('%icon', '[img=' .. Item_ore_fluid .. '.' .. item_name .. ']'):gsub('%item_name', item_name2):gsub('%backer_name', entity.backer_name):gs
Your new code has `::` which is a syntax error. Also I was more trying to describe, sorry if that was unclear:
```lua
entity.backer_name = config.station_name
    :gsub('%icon', '[img=' .. Item_ore_fluid .. '.' .. item_name .. ']')
    :gsub('%item_name', item_name2)
    :gsub('%backer_name', entity.backer_name)
    -- etc
```

2023-03-15 17:47 UTC, Cooldude2606 commented on modules/commands/bot_queue.lua
> +    return Commands.success
You new code includes both, if you want both then please make them different messages.

2023-03-20 00:16 UTC, Cooldude2606 reviewed
No issues with addons and commands. Comments relating to control modules are below. You will need to split some of these files into distinct modules.

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/research.lua
> +    return Commands.success
Please return a message saying the current state of auto research.

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/research.lua
> +local res_queue_enable = false
`Global` is not used, this will desync.

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/research.lua
> +Commands.new_command('auto-research', 'Automatically queue up research')
This file impliments a command, this should not be stored within `modules/control`

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/research.lua
> +if config.enabled then
Don't need `enabled` within config when the file only impliments a single feature.

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/research.lua
> +local inf_res = {
This should be in the config to allow for easy adjustment for using this in a modded scenario.

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/research.lua
> +local config_bonus = require 'config.bonus' --- @dep config.bonus
This should be an optional require which you test for. See `_C.opt_require`

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +end
Do not need `enabled` within config.

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +global.vlayer.storage.item['accumulator'] = 0
Use `Global` to avoid conflicts. If you can't work out how to use it then use the version in `factorio_control.lua`

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +        circuit_i.get_or_create_control_behavior().set_signal(8, {signal={type='item', name='accumulator'}, count=1})
Don't call `get_or_create_control_behavior` multiple times, use a variable.

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +end)
Move the GUI code to a new module within `modules/gui`. Then I will review the GUI code.

2023-03-20 00:16 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +Commands.new_command('personal-battery-recharge', 'Recharge Player Battery with vlayer')
Move the command code to a new module within modules/commands` Then I will reiview the command code.

2023-03-20 22:54 UTC, Cooldude2606 reviewed
Addons, commands, control and data reviewed. Gui and config have not been reviewed.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/commands/research.lua
> +local config = require 'config.research' --- @dep config.research
`Event` and `config` are both unused.
`Global` is used but does nothing.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/commands/research.lua
> +end)
`global` is not used, this code does nothing.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/commands/research.lua
> +        res_queue(player.force)
`res_queue` does not exist. Were you meant to import `modules.control.research` ?

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/commands/vlayer.lua
> +end)
Why is there a command for waterfill here? Should this not be its own module. Moreover, this command would be really slow to use if you can only change one tile at a time. Try using our `Selection` module.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/commands/vlayer.lua
> +end)
You are using `global` here when I suspect you were wanting to import from `modules.control.vlayer` not importing will cause unexpected behaviour.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/control/miner.lua
> +    local function auto_handle(event)
I meant move the function body, not the function. Remove line 4 and 61 and remove one level on indentation.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +local Roles = require 'expcore.roles' --- @dep expcore.roles
`Roles` is not used. Please Remove.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/data/bonus.lua
> +    apply_bonus(player)
`stage` is nil and can not be compared to number on line 33.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/data/bonus.lua
> +    end
Why is there logic to set stage in the apply function? This will cause a disparity between what the player sets and whatt they experience.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/data/bonus.lua
> +            player[config.player_bonus[k].name] = config.player_bonus[k].max * stage / 10
A minimum value needs to be considered because not all values are 0 by default.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/data/bonus.lua
> +    apply_bonus(game.players[player_name], pb or 0)
Why are you renaming variables to be less descriptive.

2023-03-20 22:54 UTC, Cooldude2606 commented on modules/data/personal-logistic.lua
> +local config = require 'config.personal_logistic' --- @dep config.personal-logistic
So much of this file should be stored in config. Please re-structure this module to be expandable by only modifying the config, such as using dicts and array. If you can't do this then please ask and I can provide an more detailed explaination.

2023-04-03 20:30 UTC, PHIDIAS0303 commented
fixed some issue on vlayer and research

2023-04-04 20:13 UTC, Cooldude2606 reviewed
All modules reviewed. I still have not reviewed the config files and will do so once changes are made to the modules.

2023-04-04 20:13 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +local function vlayer_convert_chest(player)
For discussion, is getting the cloest chest better than using `player.selected` ? I would argue that using `player.selected` gives better control over which chest is converted, and if you still want to enforce a set radius then you can check the distance between the player and the selected chest. See `commands/ratio` for an example of `player.selected` being used.

2023-04-04 20:13 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +        local entity = player.surface.get_closest(player.position, entities)
If you are looping over all entities, why are you getting the cloest one? Use `for _, entity in pairs(entities) do`

2023-04-04 20:13 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +local button_power =
I will accept these buttons for now. But a to-do task is to have the buttons become disabled when the maxed is reached, similar to how the new warp button can not be pressed when you are too close to a warp point.

2023-04-04 20:13 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +    if Roles.player_allowed(player, 'vlayer-2') then
`vlayer-2` is not descriptive enough for what this permission allows.

2023-04-04 20:13 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +    scroll_table.add{
Almost all of these do not require names, and all use the same style. Therefore a custom gui template can be used where the caption is provided by an argument. Message me if you need assistance with this change.

2023-04-04 20:13 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +
Add `local tbl = container.scroll.table` to avoid repeatitve indexing.

2023-04-05 05:18 UTC, PHIDIAS0303 commented on modules/gui/warp-list.lua
> +        spawn_id = Warps.add_warp(force.name, player.surface, spawn_position, nil, 'spawn')
all force is lowercase like player and neutral so it should also be lower case

2023-04-05 05:20 UTC, PHIDIAS0303 commented on modules/gui/readme.lua
>              end
it is just revert as not going to update it with the new stuff

2023-04-05 17:32 UTC, PHIDIAS0303 commented on modules/gui/vlayer.lua
> +local function vlayer_convert_chest(player)
you cannot select item when pressing button

2023-04-15 17:04 UTC, Cooldude2606 requested changes

2023-04-15 17:04 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +        g.container.scroll.table = frame.container.scroll.table
This doesn't work.

2023-04-15 17:04 UTC, Cooldude2606 commented on modules/gui/warp-list.lua
> +        spawn_id = Warps.add_warp(force.name, player.surface, spawn_position, nil, 'spawn')
This is not a force. It is the name of the warp displayed in the list.

2023-04-22 23:41 UTC, Cooldude2606 commented on modules/commands/cheat-mode.lua
> +Commands.new_command('toggle-always-day', 'Toggles always day in surface')
Your edit has indroduced the `player` argument, could you make it `surface` instead. There is an argument type for this already, so its a small change to what you already have.

2023-04-24 01:01 UTC, Cooldude2606 requested changes
A few more edits.

2023-04-24 06:36 UTC, PHIDIAS0303 commented on modules/gui/research.lua
> +			research.display[i].p = format_time(research.res[event.research.name].time=, {hours=true, minutes=true, seconds=true, string=true, null=true})
so i havent mark the conversation done

2023-05-09 11:10 UTC, Cooldude2606 requested changes

2023-05-09 11:10 UTC, Cooldude2606 commented on modules/gui/research.lua
> +research.res_total = 0
This value is static and calculated from the config only. Therefore it does not need to be in global.

2023-05-09 11:10 UTC, Cooldude2606 commented on modules/gui/research.lua
> +research.res_total = 0
This value is static and calculated from the config. So it does not need to be in global.

2023-05-09 11:10 UTC, Cooldude2606 commented on modules/gui/research.lua
> +				research.res_n = research.res[v].order
`order` is not required because `for order, v in pairs(res) do`

2023-05-09 11:10 UTC, Cooldude2606 commented on modules/gui/research.lua
> +			if research.res[res[research.res_n + i - 3]] ~= nil then
Make `research.res[res[research.res_n + i - 3]]` into a local variable, no reason to keep calculating it.

2023-05-09 11:10 UTC, Cooldude2606 commented on modules/gui/research.lua
> +	end
Why is `res_n` in global? it works just fine as a local variable.

2023-05-09 11:10 UTC, Cooldude2606 commented on modules/gui/research.lua
> +				research.res_n = research.res[v].order
`.order` is not required because of `for order, v in pairs(res) do`

2023-05-09 12:35 UTC, PHIDIAS0303 commented on modules/gui/debug/main_view.lua
> +
it can move but other part will also need to modify.

2023-05-13 16:46 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +    if config.always_day or game.players[1].surface.always_day then
`game.players[1].surface.always_day` should be `game.surfaces['nauvis'].always_day` to be consistent with the code below. And so mods which allow the player to change surface do not impact this code.

2023-05-13 16:46 UTC, Cooldude2606 commented on modules/gui/research.lua
> +	end
Please move this into a function `get_res_n` and remove the varible from the file scope (line 20)
New usage `local res_n = get_res_n()` same for lines 102 to 111.

2023-05-13 16:46 UTC, Cooldude2606 commented on modules/gui/research.lua
> +local res = {}
`res[i].time` needs to be in global. Everything else can be calculated from this value and does not need to be stored.

2023-05-18 14:57 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +local function vlayer_convert_chest(player)
You can select an entity while typing in chat, this is how `/ratio` works.

2023-05-18 15:09 UTC, Cooldude2606 requested changes

2023-05-18 16:07 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +local function vlayer_convert_chest(player)
My bad, this needs to work with a gui button, so `player.selected` would not work.

2023-05-19 12:58 UTC, Cooldude2606 reviewed
While there are still lots of minor changes relating to style and optimisations. I feel the code is at least able to function without the risk of errors. Therefore I will now start a review of the config.

2023-05-19 13:35 UTC, Cooldude2606 requested changes

2023-05-19 13:35 UTC, Cooldude2606 commented on config/expcore/roles.lua
Do not modify colours or role overrides. Do not change allowed permissions other than adding those related to new features.

2023-05-19 13:35 UTC, Cooldude2606 commented on config/gui/warps.lua
> +    cooldown_duration = 30, --- @setting cooldown_duration the duration of the warp cooldown in seconds
This will need discussion for balancing considerations.

2023-05-19 13:35 UTC, Cooldude2606 commented on config/advanced_start.lua
Do not modify existing config. `armor.enable` should be `false` and renamed to `armor.enabled`

2023-05-19 13:35 UTC, Cooldude2606 commented on modules/data/bonus.lua
> +            game.players[event.player_index].surface[v.name] = v.max
This should also be `+ v.max` to be consistent with how the other bonuses are applied.

2023-05-19 13:35 UTC, Cooldude2606 commented on config/discord_alerts.lua
Do not modify this file.

2023-05-19 13:35 UTC, Cooldude2606 commented on config/repair.lua
Do not modify this file.

2023-05-19 13:35 UTC, Cooldude2606 commented on config/spawn_area.lua
Do not modify this file other than the addion of `spawn_area.tile_radius` and the new resource settings.

2023-05-19 13:35 UTC, Cooldude2606 commented on modules/data/personal-logistic.lua
> +                s(config.start + v.key, {min=math.floor(v.min * amount), max=math.floor(v.max * amount), name=k})
Line 26 is the same as line 42. Therefore line 24 can be changed to `v.upgrade_of ~= nil and v.type ~= nil`

2023-05-27 21:54 UTC, Cooldude2606 commented on config/expcore/roles.lua
> +    'bonus-1',
Will need to discuse with the others about adding this to member.

2023-05-27 21:54 UTC, Cooldude2606 commented on config/expcore/roles.lua
> +    ['PHIDIAS0303']={'Senior Administrator', 'Moderator', 'Board Member', 'Member'},
You will need to remember to remove SA from your self here.

2023-05-27 21:54 UTC, Cooldude2606 commented on config/expcore/roles.lua
> +    'bonus-2',
Please make this permission `command/bonus/level-2`

2023-05-27 21:54 UTC, Cooldude2606 commented on config/expcore/roles.lua
> +    'bonus-1',
`bonus-1` is not required because you never test for it in the code. Anyone with access to `command/bonus` can be assumed to have "level 1"

2023-05-27 21:54 UTC, Cooldude2606 commented on config/advanced_start.lua
Neither part of this comment has not been resovled.

2023-05-27 21:54 UTC, Cooldude2606 commented on config/bonus.lua
> +return {
It has been decided amoung the admins that the levels of bonus should be configured here. This means having a list of the permissions, and the max bonus each one gives. Also for our server we would want only 10% (so 1) allowed at level 1, not the 20% you have hard coded.
```lua
bonus_levels = { -- ["permission"] = x*+10%
    ["command/bonus"] = 1,
    ["command/bonus/level-2"] = 10
}
```

2023-05-27 21:54 UTC, Cooldude2606 commented on config/spawn_area.lua
Comment has not been addressed, file still has changes present.

2023-07-16 18:31 UTC, Cooldude2606 commented on config/expcore/roles.lua
Colours are still being modified, so this is unresovled.

2023-07-16 18:47 UTC, Cooldude2606 requested changes
Only three comments this time, we are getting very close now. Also sorry for the delay on this review I had other things to attend to.

2023-07-16 18:47 UTC, Cooldude2606 commented on config/bonus.lua
> +    player_bonus_level = 1,
While your solution does allow configuration to the extent needed, it will need a comment to explain what the value means because currently it is hard to understand from a cold read.

2023-07-16 18:47 UTC, Cooldude2606 commented on config/spawn_area.lua
There are still changes in this file which have not been reverted. `deconstruction_tile` should be `concrete` and `pattern_tile` should be `stone-path`. Therefore this comment is not resolved.

2023-07-16 18:47 UTC, Cooldude2606 commented on config/vlayer.lua
> +        enabled = false,
This feature looks complete now, can you change this to `true`

2023-07-29 13:58 UTC, Cooldude2606 commented on modules/addons/deconlog.lua
> +		game.print(player.name .. " tried to deconstruct the area " .. pos_to_gps_string(e.area.left_top) .. " to " .. pos_to_gps_string(e.area.right_bottom) .. " but were not allowed.")
I don't think this `game.print` is useful, because this triggers for anyone who has decon permissions but not `deconlog-bypass` you need to be checking for `standard-decon` ie:
```lua
if Roles.player_has_flag(player, "deconlog-bypass") then
    return
elseif not Roles.player_has_flag(player, "standard-decon") then
    game.print()
end
add_log()
```
It would be even better if you changed this so it only prints to admins. See example code in reports.lua

2023-07-29 15:40 UTC, Cooldude2606 reviewed
LGTM. Please no more changes as I would like to start in game testing now.

2023-08-05 17:17 UTC, Cooldude2606 commented
## In-game Testing: Addons
There were no issues found in the addons other than those listed below, please make changes to resolve these issues and only these issues.
### Advanced Start
- Config property is named "Grid" when it does not insert any items into the armour grid. This should either be renamed to "Items" or have the feature adjusted to automatically insert the items into the armour grid.
### Decon Log
- When a message is printed to game chat it states that the player was not allowed to decon. This is false because it will print even when tree and rocks are the only things being removed (which guests are allowed to remove). This message will become unhelpful because of how generic the trigger is, further more new players will not be aware that they cant use the decon planner and you will get lots of false positives. I advise you add a new condition which only prints to chat if there are more than a certain number of machines in an area.
- The log for shooting rockets/nukes will trigger when when the ammo is refilled or swapped to another type. However this is not related to this PR so will be raised as a separate issue and does not need a fix within this PR.
### Report Jail
- Please add a comment to say how long "108000" is, or rewrite it in another form such as `60*60*30` to show that it is 30 minutes.
### Spawn Area
- By setting "spawn" as a friend of "player" it allows people to use inserters to remove the ammo from the turrets, this opens up the ability to get infinite free uranium ammo. There is no way to prevent this other than having it on a different force which is why the "spawn" force was created. Please revert these changes so that the player force and spawn force are not friends and all chests on the neutral force to allow player interaction.
- Can you make it so the default resource spawn areas are in the four diagonal directions rather than in a straight line on the left side. Uranium can be to the north and oil to the south.
- The resource refill does not refill the created patches, instead it refills based on proximity to 0,0 which is not expected behaviour. Please update this to refill the generated patches.
- You have the resource refill function inside the creation event rather than the on tick event, this means that it is never getting called an no resources are being refilled at all. Please move this to the on_nth_tick event similar to turret refill. Don't put it into the same event as the refill times should not necessarily be the same.
### Station Auto Name
- I placed a station at spawn close to iron and copper and got this name `[L] %[img=it-21.5m.-21.5opp-21.5r-or-21.5]` something is clearly not right. This appears to be a result of lua pattern matching using `%x` for all hexadecimal characters. Because of this we should account using `%` in the config and instead switch to `__icon__` `__item_name__` `__pos_x__` etc
- X and Y values should be based on the entity position not the bounding box, also they should be floored to avoid decimals.

2023-08-07 20:26 UTC, Cooldude2606 commented on modules/addons/deconlog.lua
> +		if ((e.area.left_top.x + e.area.right_bottom.x) * (e.area.left_top.y + e.area.right_bottom.y)) > 10000 then
This maths is wrong. It also would be better to check the number of entites in an area.
```suggestion
		if e.surface.find_entities_filtered{ area = e.area, force = e.player.force, invert = true } > 250 then
```

2023-08-07 20:31 UTC, Cooldude2606 commented on modules/addons/spawn-area.lua
> +        end
Using this will cause the refill to only happen once. Remove this elseif clause.

2023-08-07 20:32 UTC, Cooldude2606 commented on modules/addons/spawn-area.lua
> +        entity = surface.create_entity{name=entity[1], position=pos, force='spawn'}
Force being "spawn" prevents the chests from being openned
```suggestion
        entity = surface.create_entity{name=entity[1], position=pos, force='neutral'}
```

2023-08-07 20:37 UTC, Cooldude2606 commented on modules/addons/station-auto-name.lua
> +                    :gsub('__y__', math.floor(entity.position.left_top.y))
This code is invalid and raises an error.
```suggestion
                    :gsub('__x__', math.floor(entity.position.x))
                    :gsub('__y__', math.floor(entity.position.y))
```

2023-08-07 22:29 UTC, Cooldude2606 commented
## In-game Testing: Commands
Firstly, the following issues are fixed: Advanced Start and Report Jail. The rest remain open as per my comments above.
Here are the issues found with the commands:

### Bot Queue
- The limit of 3 is quite low for our server, this can be increased to 20
- When setting the values you have 1 and 3 reversed, success should be 3\*amount and failure should be 1\*amount
- The first argument to a command is `player` please use this and not `game.player`

### Enemy
- Invalid permission to use `/kill-biters` and `/remove-biters`

### Friendly Fire
- As with the other commands, please allow the user to specify a force to change the friendly fire state of. With the default being the players force.

### Lawnmower
- This command deletes your character, this can not happen. Worse still it deletes all entities. Remove the `invert` from the search.

### Pollution
- Please allow the user to select a surface for pollution clear, with the default being their current surface.
- Using `/pol-off` does not remove pollution from the surface. Please make this command remove pollution from all surfaces.
- Please give the commands full names `/pollution-clear` and `/pollution-off`

### Auto Research
- `event.by_script` in `research_notification` should only effect `game.print` the rest of the logic should still be triggered to avoid unexpected behaviour.
- The logic used for the inventory bonus makes no sense. At Level 4, `mining_drill_productivity_bonus = 0.4` which equates the following:
	- `(event.research.force.mining_drill_productivity_bonus * 100) <= (config.bonus_inventory.limit * 10 / config.bonus_inventory.rate)` to `40 <= 20*10/5` 
	- `math.floor(event.research.force.mining_drill_productivity_bonus * 100) * config.bonus_inventory.rate + 10` to `40 * 5 + 10 = 210`
- This more than triples the inventory size, and what does the `/ config.bonus_inventory.rate` achieve in the condition?
- Please explain what the indented logic is here so I can suggest a sensible implementation.

### Speed
- Invalid role permission for the command.

### Waterfill
- Unknown locale key `vlayer.waterfill-cliff` and all other locale keys for this command. This should not be vlayer.
- The command does not remove any cliff explosives from your inventory when it should.
- Testing if the player position is the same as the entity is useless because of floating point comparisons.
- Only one chest gets removed, and it doesnt even place down any water. This is because you are attempting to access the entity (steel chest) position after you have destroyed it.
- Why are you even using steel chests? It would be better to check if the selected area is empty of all entities, and if it is then replace all tiles with water.

2023-08-08 18:03 UTC, Cooldude2606 commented
## In-game Testing: Control, Data & GUIs
This covers the remaining sections of the code in this PR.

### Miner
- This is an addon not a control module, please move it to the correct folder
- The current code does not have a 100% success rate, some depleted miners do not get marked for deconstruction.
- This is because of the use of `return` during the for loop over `entities`, the issue is fixed if the loop body is moved to its own function

### Vlayer
- The GUI raises an error for players who can not edit the vlayer interface. This is because you are trying to use custom names like `button_1` rather than using `button_power.name`
- The circuit input does nothing, why does it exist? Please remove it or justify it.
- The UI could use some work, but I am happy for this to be done at a later date.
- The UI buttons never get disabled when above the interface limit.
- The UI button to remove an interface does not work at all.

### Bonus
- Mods should be `command/bonus` not `command/bonus/2`

### Personal Logistics
- Invalid role permissions, cant use command
- Using `0` as an argument should clear the automatic settings, not set them all to 0.
- I feel we need tiers to these requests, because why would you want all three kinds of belt and all three types of assembler?
- If you dont want to implement tiers then you should configure this for late game, so you request different amounts of each tier with a preference to higher tier; also things like stone furnaces and assembling machine 1s should always be trashed.

### Research
- When `/cheat all` is used it breaks the Gui because `res_i[event.research.name]` is nil on line 154. This error is also caused by using `/research-all`
- Completing any research that is not in the list will also raise this same error.

### Server UPS
- The percentage you added does not work, you need to times it by 100.
- The label has been moved to overlap with the multiplayer statistics, previously I was unaware of the overlap with the clock, so i propose we drop the label `SUPS =` and just have the number under the ups number but right of the clock. (-362, 30)

### Warps
- Error message for creating a warp too close to other entities was not updated to match changed radius. Line 122 change 4.5 to 2.5.

2023-08-08 18:29 UTC, Cooldude2606 commented on modules/addons/deconlog.lua
> +		local items = e.surface.find_entities_filtered{area=e.area, force=e.player.force}
This was my mistake as you used my example. `e.player` should just be `player`

2023-08-08 18:43 UTC, Cooldude2606 commented on modules/commands/waterfill.lua
> +                if (math.floor(player.position.x) ~= math.floor(entity.position.x)) and (math.floor(player.position.y) ~= math.floor(entity.position.y)) then
This boolean logic is wrong. This should be an "or" because of the negation. `¬(A && B) => ¬A || ¬B`

2023-08-10 23:39 UTC, Cooldude2606 requested changes
Please make the highlighted changes, also here is a list of the remaining open issues from previous tests:

**Spawn Area** - Can you make it so the default resource spawn areas are in the four diagonal directions rather than in a straight line on the left side.

**Pollution** - Please add a loop which removes pollution from all surfaces when `/pol-off` is used.

**Vlayer** - The UI buttons still do not get disabled when the interface limit is reached.

**Research** - Log is filled with errors when any research is completed that is not on the tracker.

2023-08-10 23:39 UTC, Cooldude2606 commented on modules/data/personal-logistic.lua
> +            local v_max = math.floor(v.max * amount)
This needs to be `math.ceil` otherwise things like power armour will be trashed unless you use `amount = 10 / 10`

2023-08-10 23:39 UTC, Cooldude2606 commented on modules/addons/spawn-area.lua
> +        end
You still refer to `resource_refill` here when it needs to be `resource_refill_nearby`

2023-08-13 20:10 UTC, Cooldude2606 requested changes

2023-08-13 20:10 UTC, Cooldude2606 commented on modules/gui/server-ups.lua
> +    label.location = {x=res.width-362*uis, y=30*uis}
Please make this `-374` rather than `-362`

2023-08-13 20:10 UTC, Cooldude2606 commented on modules/gui/server-ups.lua
> +        local caption = ' / '.. External.get_server_ups() .. ' (' .. string.format('%.1f ', External.get_server_ups() * 5 / 3) .. '%)'
Please make this `'/ '` rather than `' / '`

2023-08-13 20:10 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +        frame.container.scroll.table['button_3'].enabled = button_circuit_enabled
The vlayer buttons still do not deactivate when above the limit. Getting an error here for `attempt to index field 'button_1' (a nil value)`. This is again because you are using `'button_1'` rather than `button_power.name`. Also note that you will need to move the update function below the button definations so that you can access their values.

2023-08-14 17:44 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +            vlayer[config.on_remove.a][config.on_remove.b] = nil
This won't work as the rest of your code expects this value to be a table/array. The lazy fix is to add three new loops after this loop for each of the array, and check that the entity is still valid, and if not then set that index to nil. The better way is to search each array and remove the matching element. Please impliment one of these approaches.

2023-08-15 17:45 UTC, Cooldude2606 approved these changes
All looks good to me. I'm happy that all my previous comments have been addressed. There is still room for improvement but those are can be saved for another PR.

2023-08-15 17:47 UTC, merged