2nd cmd of personal logistics. also for spidertron
explosivegaming/scenario pull request #249
Opened 2023-09-23 12:25 UTC by PHIDIAS0303

2023-09-23 17:23 UTC, Cooldude2606 requested changes
Small improvements can be made, but functionaly is all correct.

2023-09-23 17:23 UTC, Cooldude2606 commented on modules/data/personal-logistic.lua
> +            if player.selected.name ~= nil then
`name` is never nil. This check is not required.

2023-09-23 17:23 UTC, Cooldude2606 commented on modules/data/personal-logistic.lua
> +            return
There is no benifit to include "clear" in this function. Either make it into its own function or place the for loop directly in the command body.
After you have done this there will be no difference between "player" (`p`) and "selected" (`s`) so you can remove type from the arguments and set `c` and `s` unconditionally.

2023-09-24 17:07 UTC, Cooldude2606 approved these changes
All looks good. You can still have the second command if you want, my change request was that it should be in its own function.

2023-09-24 17:29 UTC, PHIDIAS0303 commented
it is not really needed for the 2nd cmd i think

2023-09-25 20:20 UTC, merged