CCTV module
explosivegaming/scenario pull request #251
Opened 2023-09-25 13:46 UTC by PHIDIAS0303

2023-09-25 20:30 UTC, Cooldude2606 requested changes
Code is not runtime safe so must be changed.

2023-09-25 20:30 UTC, Cooldude2606 commented on modules/gui/surveillance.lua
> +        Gui.element{
Don't define new elements inside another element, because this will cause a new element to be defined for every player. Also `Gui.element` is not runtime safe but I forgot to include the runtime assertion which is why it did not error.

2023-09-25 20:30 UTC, Cooldude2606 commented on modules/gui/surveillance.lua
> +end)
Rather than `, function(_) gui_update() end)` you can use `, gui_update)`

2023-09-25 20:30 UTC, Cooldude2606 commented on modules/gui/surveillance.lua
> +Event.on_nth_tick(1, function()
Don't use `on_nth_tick(1,` use `on_tick` or `on_player_moved`

2023-10-02 16:29 UTC, PHIDIAS0303 commented
i have no idea what i am doing

2023-10-03 23:14 UTC, Cooldude2606 reviewed
Two small changes need, mostly around the size of buttons.
Could you make the cameras disabled by default, it feels odd to have both enabled on your player by default.
Once that is complete it can be merged.

2023-10-03 23:14 UTC, Cooldude2606 commented on modules/gui/surveillance.lua
> +    element.parent.parent.cctv_display.position = player.position
Very simple correction here, this one is probably on me when I changed the GUI structure.
```suggestion
    element.parent.parent.parent.cctv_display.position = player.position
```

2023-10-04 22:12 UTC, Cooldude2606 commented on modules/gui/surveillance.lua
> +    local container = Gui.container(parent, event_trigger, 480)
I didn't realise until testing, but we need a scroll pane here to stop the built in one from showing up.
400 seams like a good size because it fits one set of buttons and one camera.
You will also need to change `camera_set(container,` to `camera_set(scroll,` and change `gui_update` and `on_tick`
```lua
local scroll = container.add{ name="scroll", type="scroll-pane", direction="vertical" }
scroll.style.maximal_height = 400
```

2023-10-07 01:31 UTC, Cooldude2606 commented on modules/gui/surveillance.lua
> +    scroll.style.maximal_height = 816
`maximal_height` must be `705` or less to prevent the external scroll bar.

2023-10-10 01:03 UTC, Cooldude2606 commented
When a player leaves the game they are removed from the selection list. This results in the selected index returning `0` for "none selected". You need to include a check for this in on_tick to prevent error spam in the logs.
`Given player value (0) is too small, the data type allows values from 1 to 65536`

2023-12-21 19:56 UTC, Cooldude2606 approved these changes
LGTM. All changes accounted for. Gui could be improved, but it works.

2023-12-21 19:57 UTC, merged