playerdata
explosivegaming/scenario pull request #256
Opened 2023-10-05 08:02 UTC by PHIDIAS0303

2023-10-05 09:32 UTC, PHIDIAS0303 commented
#226

2023-10-07 01:49 UTC, Cooldude2606 requested changes
It would be nice if changing the selected player would update the labels automatically. You can do this by moving the button on_click into a `update_labels` function which is used by both the on click and on selection change.

Also a big FYI, the player data stats are designed to be iterable. See the readme window for an example:
```lua
for _, name in pairs(PlayerData.Statistics.metadata.display_order) do
    local child = PlayerData.Statistics[name]
    local metadata = child.metadata
    local value = child:get(player_name)
    if value ~= nil or metadata.show_always then
        if metadata.stringify then
            value = metadata.stringify(value)
        else
            value = format_number(value or 0)
        end
        Gui.centered_label(statistics, 150, metadata.name or {'exp-statistics.'..name}, metadata.tooltip or {'exp-statistics.'..name..'-tooltip'})
        Gui.centered_label(statistics, 130, {'readme.data-format', value, metadata.unit or ''}, metadata.value_tooltip or {'exp-statistics.'..name..'-tooltip'})
    end
end
```

2023-10-10 01:16 UTC, Cooldude2606 requested changes

2023-10-10 01:16 UTC, Cooldude2606 commented on modules/gui/playerdata.lua
> +    local table = container['pd_st_2'].disp.table
This needs to be `pd_st_1` not `2`. 
`modules/gui/playerdata.lua:731: attempt to index field '?' (a nil value)`

2023-10-10 01:16 UTC, Cooldude2606 commented on modules/gui/playerdata.lua
> +    table[pd_username_player.name].width = 224
This needs to be `.style.width`.
`LuaGuiElement doesn't contain key width.`

2023-10-10 01:16 UTC, Cooldude2606 commented on config/expcore/roles.lua
> +    'gui/playerdata'
Can you also give the permission `gui/playerdata` to `Moderator`.

2023-10-10 01:16 UTC, Cooldude2606 commented on modules/gui/playerdata.lua
> +    local player_name = game.players[element.parent[pd_username_player.name].selected_index]
You need to consider the case when `selected_index` is `0` because a player has left the game.

2023-10-10 01:16 UTC, Cooldude2606 commented on modules/gui/playerdata.lua
> +    for _, player in pairs(game.players) do
This must be `game.connected_players` because player data is not valid for offline players.

2023-12-22 19:47 UTC, Cooldude2606 reviewed
Concept works, I have cleaned up alot of it tho. Could you please review it yourself to confirm all functions are the same as you intended.

2023-12-23 20:14 UTC, merged