vlayer
explosivegaming/scenario pull request #296
Opened 2024-06-05 08:38 UTC by PHIDIAS0303

2024-06-05 18:29 UTC, Cooldude2606 requested changes

2024-06-05 18:29 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +        player.print{'vlayer.steel-chest-detect'}
```suggestion
        player.print{'vlayer.steel-chest-empty'}
```

2024-06-05 18:29 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +    tooltip = {'vlayer.display-remaining_surface_area-tooltip'},
Should use `-` not `_`

2024-06-05 18:29 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +        table.insert(full_list, i)
Would be better if this was coordinates rather than just a number.

2024-06-05 18:29 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +    local interface_type, interface_position = vlayer.remove_interface(vlayer.get_interfaces()[vlayer_control_type_list[target]][n].surface, vlayer.get_interfaces()[vlayer_control_type_list[target]][
Put `vlayer.get_interfaces()[vlayer_control_type_list[target]` into a variable.

2024-06-05 18:29 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +                end
```suggestion
                to_burn = math.min(v.count, max_burning / v.value)
```

2024-06-05 18:29 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +                vlayer_data.storage.energy = vlayer_data.storage.energy + (to_burn * v.value)
You also need to update `max_burning` so that the next item does not produce too much

2024-06-05 18:29 UTC, Cooldude2606 commented on locale/en/gui.cfg
> +display-current-capacity-tooltip=Battery Current Charge
Would help a lot to have units listed here, eg MJ or MW.

2024-06-05 18:29 UTC, Cooldude2606 commented on locale/en/gui.cfg
> +main-tooltip=vlayer GUI
```suggestion
main-tooltip=Vlayer
```

2024-06-05 18:29 UTC, Cooldude2606 commented on config/vlayer.lua
> +        }
Coal should not be here by default, it is not trash and must be intentionally mined. The amount gained from large rocks is not sufficient when it can be easily abused.

2024-06-12 20:40 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +    tooltip = {'vlayer.display-remaining_surface_area-tooltip'},
Line 114 has not been changed.

2024-06-12 20:45 UTC, Cooldude2606 commented on locale/en/gui.cfg
> +main-tooltip=vlayer GUI
Should be "V" not "v" to match style of other GUIs.

2024-06-12 20:47 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +        local max_burning
This does not need to be in this scope.

2024-06-12 20:55 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +    local interface_type, interface_position = vlayer.remove_interface(t[n].surface, t[n].position)
`attempt to index field '?' (a nil value)`
Need a nil check here, or a length check on t against n.

2024-06-12 21:00 UTC, Cooldude2606 requested changes
Removing an interface does not refresh the dropdown which leads to unexpected behaviour. I would recommend creating a custom event for this if you understand how. If not making refresh into a function will be sufficient and having it called for all players when adding or removing an interface.

2024-06-13 15:34 UTC, PHIDIAS0303 commented on locale/en/gui.cfg
> +main-tooltip=vlayer GUI
that dont look good

2024-06-20 17:16 UTC, Cooldude2606 requested changes
Switching interface type should also call `vlayer_gui_List_refresh`

2024-06-20 17:16 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +            table.insert(full_list, i .. ' X ' .. interface[i].position.x .. ' Y '.. interface[i].position.y)
`attempt to call field 'insert' (a nil value)`
Do not use `table` as a variable name on line 293.

2024-06-20 17:16 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +    table[vlayer_gui_control_build].visible = visible
```suggestion
    table[vlayer_gui_control_build.name].visible = visible
```

2024-06-21 20:31 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +            if v.count > 0 then
```suggestion
            if v.count > 0 and max_burning > 0 then
```
This change is needed otherwise when the stored energy is above 50% it will start consuming power to create wood.

2024-06-22 15:40 UTC, Cooldude2606 approved these changes

2024-06-22 15:40 UTC, merged