Bonus GUI
explosivegaming/scenario pull request #300
Opened 2024-07-09 13:46 UTC by PHIDIAS0303

2024-07-18 19:26 UTC, Cooldude2606 requested changes
Some changes needed; although I'll also comment on discord as some things can be done to make this much easier on yourself.
Also don't use `tonumber(element.caption)` when you can instead get the value directly from the slider.

2024-07-18 19:26 UTC, Cooldude2606 commented on modules/data/bonus.lua
> +                player[v.combined_bonus[i]] = v.value * stage / 10
From my understanding that `value` is the start / base value, this math would not work. Are you able to clarify this.

2024-07-18 19:26 UTC, Cooldude2606 commented on locale/en/gui.cfg
> +display-cmms=CMMS
Rather than using acronyms, shorthands will be better such as `Mining` `Running` `Inventory` etc

2024-07-19 05:48 UTC, PHIDIAS0303 commented on locale/en/gui.cfg
> +display-cmms=CMMS
it is too long

2024-07-19 15:37 UTC, PHIDIAS0303 commented on modules/data/bonus.lua
> +                player[v.combined_bonus[i]] = v.value * stage / 10
the value is just the bonus 10 in the old days.

2024-07-20 14:19 UTC, PHIDIAS0303 commented on config/bonus.lua
> +            cost = 10
value is the default bonus 10 of the old days. max allow it to be changed even more. or just less if player don't need it.
the scale is the minimum of how much you can move.
the cost scale is how much points needed, each cost can give you how many cost scale

2024-07-27 23:37 UTC, Cooldude2606 commented on locale/en/gui.cfg
> +display-cmms=CMMS
Could you explain why you are opposed to using more readable names?

2024-07-28 04:29 UTC, PHIDIAS0303 commented on locale/en/gui.cfg
> +display-cmms=CMMS
they are just not updated i think

2024-07-28 19:30 UTC, Cooldude2606 requested changes
See discord for suggested changes to the config file.

2024-07-28 19:30 UTC, Cooldude2606 commented on modules/gui/bonus.lua
> +end)
Because the values update automatically, it would be a lot more useful for this button to reset the sliders to the players current bonus. (Kind of like a 'cancel changes' button)

2024-07-28 19:30 UTC, Cooldude2606 commented on modules/gui/bonus.lua
> +    bonus_gui_control_pts_r_count(disp)
Should set the two count labels here rather than needing to manually refresh when you join.

2024-07-28 19:30 UTC, Cooldude2606 commented on modules/gui/bonus.lua
> +    element.parent[element.tags.counter].caption = element.slider_value
Would be nice if the percentage based bonuses (Mining/Running/Crafting) showed as `150%` rather than `1.5`. This can be done by adding a `is_percentage` flag from the config into `element.tags` on line 205. Then you can test for it here.

2024-07-28 19:30 UTC, Cooldude2606 commented on modules/gui/bonus.lua
> +        allow_negative = false,
These do nothing for a label, they are used to control allowed user input on text fields. They can be removed.

2024-07-29 19:58 UTC, Cooldude2606 requested changes
`on_player_died` needs to be added for instant respawn.
`on_player_respawned` to reapply bonus, make sure to check remaining >= 0.

2024-07-29 19:58 UTC, Cooldude2606 commented on locale/en/gui.cfg
> +servers-d6=This server is closed.
Why this change?

2024-07-29 19:58 UTC, Cooldude2606 commented on locale/en/commands.cfg
> -
While the command file still exists, these also need to remain.

2024-07-30 04:28 UTC, PHIDIAS0303 commented on locale/en/gui.cfg
> +servers-d6=This server is closed.
because i pasted my server one

2024-07-30 16:41 UTC, Cooldude2606 approved these changes
All code looks good to me. However, since this impacts the rewards for donators I will need to inform them before this is merged.

2024-08-10 13:11 UTC, merged