VLAYER Control
explosivegaming/scenario pull request #303
Opened 2024-07-11 11:10 UTC by PHIDIAS0303

2024-07-18 18:56 UTC, Cooldude2606 commented
This change can not be made because `surface.daytime` can be modified from other scripts.
For example if `surface.always_day` or `surface.freeze_daytime` are true then `time` will continue to tick when it should be constant.

2024-07-19 05:58 UTC, PHIDIAS0303 commented
but the main thing is that I need the tick to do the day-night calculation of solar power ...

2024-07-21 21:45 UTC, Cooldude2606 commented
> but the main thing is that I need the tick to do the day-night calculation of solar power ...

For it to be accurate for vlayer solar it must use `surface.daytime` because this is used to calculate solar power production not game tick.

2024-07-27 23:44 UTC, Cooldude2606 requested changes

2024-07-27 23:44 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +        multiplier = get_production_multiplier(),
`multiplier` is vauge, use full name `production_multiplier`

2024-07-27 23:44 UTC, Cooldude2606 commented on modules/control/vlayer.lua
> +        time = math.floor(game.tick % vlayer_data.surface.ticks_per_day)
Unable to accept the use of `game.tick` when it introduces inconsistencies. Add a `tick` property and combine with your `day_length` property in combinators if you absolutely must.

2024-08-10 13:14 UTC, Cooldude2606 requested changes
Not what I meant why I said add a tick property. I meant a `tick` signal that is equal to `game.tick` so that you can do `tick % day_length` in a combinator and return `time` to be based on `daytime`.

2024-08-24 17:25 UTC, Cooldude2606 requested changes
I really like the change to use the selection tool. It all works correctly but the error messages need improving.

2024-08-24 17:25 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +local SelectionConvertArea = 'ConvertArea'
This must be a unique string. Currently it conflicts with waterfill.
```suggestion
local SelectionConvertArea = 'VlayerConvertChest'
```

2024-08-24 17:25 UTC, Cooldude2606 commented on modules/gui/vlayer.lua
> +        player.print{'vlayer.result-unable', {'vlayer.control-type-' .. target:gsub('_', '-')}}
Can you add a reason to this, eg `Unable to build Energy interface: Multiple steel chests selected`
Also add a reason to the other places this is used. ie `At interface limit` and `Not enough room`

2024-08-31 22:09 UTC, Cooldude2606 approved these changes

2024-08-31 22:10 UTC, merged