Miner
explosivegaming/scenario pull request #318
Opened 2024-08-27 12:30 UTC by PHIDIAS0303

should be a slightly better method

2024-08-30 16:21 UTC, Cooldude2606 commented on modules/addons/miner.lua
> +    local entities = event.entity.surface.find_entities_filtered{area={{event.entity.position.x - 3, event.entity.position.y - 3}, {event.entity.position.x + 3, event.entity.position.y + 3}}, type='m
Why was this changed to 3?

2024-08-30 16:36 UTC, PHIDIAS0303 commented on modules/addons/miner.lua
> +    local entities = event.entity.surface.find_entities_filtered{area={{event.entity.position.x - 3, event.entity.position.y - 3}, {event.entity.position.x + 3, event.entity.position.y + 3}}, type='m
mining_drill_radius?

2024-08-30 20:17 UTC, PHIDIAS0303 commented
will just change to this for now, the status is having some issue sometimes

2024-08-31 22:41 UTC, Cooldude2606 commented on modules/addons/miner.lua
> +    local entities = event.entity.surface.find_entities_filtered{area={{event.entity.position.x - 3, event.entity.position.y - 3}, {event.entity.position.x + 3, event.entity.position.y + 3}}, type='m
We are searching a radius around an ore entity for a mining drill which can reach it. The value 1 is used because it is the difference between the mining radius and physical size of of the mining drill. This should remain as 1.

2024-08-31 22:54 UTC, Cooldude2606 reviewed
This is required because if a miner is marked for deconstruction in the same tick that it's resources are depleted it does not output the last ore. Instead it holds onto it in an internal inventory.

_Originally posted by @Cooldude2606 in https://github.com/explosivegaming/scenario/pull/270#discussion_r1461006714_

We can not remove the `miner_data` table unless you have seen that the above issue has been fixed. If it has not been fixed then you haven't made any material changes in this PR.

2024-08-31 22:54 UTC, Cooldude2606 commented on modules/addons/miner.lua
> -        if ((math.abs(entity.position.x - event.entity.position.x) < entity.prototype.mining_drill_radius) and (math.abs(entity.position.y - event.entity.position.y) < entity.prototype.mining_drill_r
This check is used to avoid the first call to `find_entities_filtered` within `miner_check`. Please add this condition back unless you can show it is faster to make the api call.

2024-09-01 21:11 UTC, Cooldude2606 requested changes

2024-09-01 21:11 UTC, Cooldude2606 commented on modules/addons/miner.lua
> -    local radius = 2
We are searching around a chest, it makes no sence to use the mining drill radius here. Revert this change.

2024-09-01 21:11 UTC, Cooldude2606 commented on modules/addons/miner.lua
> -        table.insert(miner_data.queue, {t=game.tick + 10, e=target})
This should remove the chest (`target`) not the miner (`entity`) also the +10 is needed so that it is guaranteed the chest is deconstructed after the miner (which is +5). So revert all changes on this line.

2024-09-05 19:02 UTC, Cooldude2606 approved these changes
Not sure why the `mining_target` check was removed, but I don't take issue with it since it makes the code simpler and its not clear if its beneficial.

2024-09-05 19:02 UTC, merged