Bonus GUI
explosivegaming/scenario pull request #327
Opened 2024-09-07 14:20 UTC by PHIDIAS0303

fix combined bonus

2024-09-14 22:21 UTC, Cooldude2606 requested changes

2024-09-14 22:21 UTC, Cooldude2606 commented on modules/gui/bonus.lua
> +
The code you currently have causes and error, and when fixed it doesn't reset the value. So you need the code below.
```suggestion
    local slider = disp['bonus_display_personal_battery_recharge_slider']
    slider.slider_value = config.player_special_bonus['personal_battery_recharge'].value
    disp[slider.tags.counter].caption = format_number(slider.slider_value)

```

2024-09-14 22:21 UTC, Cooldude2606 commented on config/bonus.lua
> +            value = 8,
This starting value is too high for the base number of points. A value of 2 would work, and although it is not centered, I do not see many people making use of it more than that.

2024-09-15 04:50 UTC, PHIDIAS0303 commented on config/bonus.lua
> +            value = 8,
it is not that high when you are using it to do robots. 4 MW each

2024-09-16 22:02 UTC, Cooldude2606 commented on config/bonus.lua
> +            value = 8,
Then please increase the base number of points, because the default exceeds it.

2024-09-20 21:31 UTC, Cooldude2606 approved these changes

2024-09-20 21:34 UTC, merged